config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    get 'site/home'
    get 'site/help'
    get 'site/about'
    get 'site/contact'

    devise_for :users
    resources :users, :only => [:show, :index]
    resources :projects
    resources :tags
    end

  # Defines the root path route ("/")
  root to: 'site#home'
end

app/models/project.rb
class Project < ApplicationRecord

  before_save { self.code = code.upcase }
  has_many :tags

  VALID_CODE_REGEX = /[A-Z][A-Z]/
  validates :code,        presence: true, length: { is: 2},
                          format: { with: VALID_CODE_REGEX },
                          uniqueness: true
  validates :title, presence: true, length: { maximum: 50 }

  def self.ransackable_attributes(auth_object = nil)
    ["code", "title", "description", "created_at", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @q = Project.ransack(params[:q])
    @pagy, @projects = pagy(@q.result, limit: 10)
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_path, status: :see_other, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:code, :title, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="container-fluid">
  <%= bootstrap_form_with(model: @project) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.text_field :code, hide_label: true,
          placeholder: t('activerecord.attributes.project.code'),
          help: t('activerecord.attributes.project.code_help') %>
    <%= f.text_field :title, hide_label: true,
          placeholder: t('activerecord.attributes.project.title'),
          help: t('activerecord.attributes.project.title_help') %>
    <%= f.text_area :description, hide_label: true,
          placeholder: t('activerecord.attributes.project.description') %>

    <div class="actions">
      <%= f.primary do %>
        <%= yield(:button_text) %>
        <%== icon('save') %>
      <% end %>
      <% if @project.persisted? %>
        <%= link_to @project, class: "btn btn-warning actions",
                data: { turbo_confirm: t('actions.sure') } do %>
                <%= t('actions.discard') %>
                <%== icon('x-square') %>
        <% end %>
      <% else %>
        <%= link_to projects_path, class: "btn btn-warning actions",
                data: { turbo_confirm: t('actions.sure') }  do %>
          <%= t('actions.discard') %>
          <%== icon('x-square') %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/projects/_old_form.html.erb
<div class="container-fluid form-horizontal">
  <%= form_with(model: @project) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="form-group row">
      <%= f.label :code, class: "control-label col-sm-1" %>
      <div class="col-sm-1">
        <%= f.text_field :code, class: "form-control",
                              placeholder: "Code" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :title, class: "control-label" %>
      <div class="col-sm-4">
        <%= f.text_field :title, class: "form-control",
                              placeholder: "Title" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :description, class: "control-label col-sm-1" %>
      <div class="col-sm-4">
        <%= f.text_area :description, class: 'form-control',
                              placeholder: "Description" %>
      </div>
    </div>

    <div class="actions">
      <%= button_tag yield(:button_text), type: 'submit',
              class: "btn btn-primary glyphicon glyphicon-record" %>
      <% if @project.persisted? %>
        <%= link_to @project, class: "btn btn-warning actions",
                data: { turbo_confirm: t('actions.sure') } do %>
                <%= t('actions.discard') %>
                <span class="glyphicon glyphicon-eye-open"></span>
        <% end %>
      <% else %>
        <%= link_to projects_path, class: "btn btn-warning" do %>
              <%= t('actions.discard') %>
              <span class="glyphicon glyphicon-eject"></span>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong><%= t('activerecord.attributes.project.code') %>:</strong>
    <%= project.code %>
  </p>
  <p>
    <strong><%= t('activerecord.attributes.project.title') %>:</strong>
    <%= project.title %>
  </p>

  <p>
    <strong><%= t('activerecord.attributes.project.description') %>:</strong>
    <%= project.description %>
  </p>

</div>

app/views/projects/edit.html.erb
<% provide(:title, t('.title')) %>
<% provide(:button_text, t('actions.save')) %>
<h2>
  <%= t('.header', project: @project.code)%>
</h2>
<%= render 'form' %>

app/views/projects/index.html.erb
<% provide(:title, t('.title')) %>
<h2>
  <%= t('.header')%>
</h2>
<div class = "container">
  <div class = 'listing'>
    <%= search_form_for @q do |f| %>
      <%= f.search_field :code_or_title_or_description_cont, class: "search_field" %>
      <%= f.button nil, class: "btn btn-primary btn-sm", action: :submit do %>
        <%== icon('search') %>
      <% end %>
    <% end %>
    <%== pagy_bootstrap_nav(@pagy) %>
    <table id='projects' class='table table-responsive table-condensed table-striped table-hoverable table-bordered' >
      <thead>
        <th scope="col"><%= sort_link(@q, :code) %></th>
        <th scope="col"><%= sort_link(@q, :title) %></th>
        <th scope="col"><%= sort_link(@q, :description) %></th>
        <th scope="col" width="120px"><%= t('table.links')%></th>
      </thead>
      <tbody>
        <% @projects.each do |p| %>
        <tr scope="row">
          <td><%= link_to p.code, project_path(p) %></td>
          <td><%= highlight p.title, params.dig(:q, :title_cont)  %></td>
          <td><%= highlight p.description, params.dig(:q, :description_cont)  %></td>
          <td>
            <%= link_to project_path(p), class: "btn btn-primary btn-sm icon-link",
                  aria: { label: t('actions.show') },
                  title: t('actions.show'),
                  display: "inline" do %>
              <%== icon('arrow-down') %>
            <% end %>
            <%= link_to edit_project_path(p), class: "btn btn-warning btn-sm icon-link",
                  aria: { label: t('actions.edit') },
                  title: t('actions.edit'),
                  display: "inline"  do %>
              <%== icon('pencil') %>
            <% end %>
            <% if current_user && current_user.admin? %>
              <%= link_to p, method: :delete, class: "btn btn-danger btn-sm icon-link",
                    aria: { label: t('actions.delete') },
                    title: t('actions.delete'),
                    display: "inline"  do %>
                <%== icon('trash') %>
              <% end %>
            <% end %>
          </td>
        </tr>

        <% end %>
      </tbody>
    </table>
    <%== pagy_bootstrap_nav(@pagy) %>
    <%== pagy_info(@pagy) %>

    <div class="left">
      <%= link_to new_project_path, class: "btn btn-primary actions" do %>
          <%= t('actions.new') + " " + t('activerecord.models.project') %>
          <span class="glyphicon glyphicon-pencil" title="new"></span>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<% provide(:title, t('.title', code: @project.code)) %>
<%# Header with navigation buttons. %>
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <ul class="navbar-nav flex-row page-heading">
      <li class="nav-item d-inline-flex p-1">
        <%= link_to projects_path,
              class: "icon-link btn btn-sm btn-secondary actions",
              title: t('actions.index') do %>
          <%== icon('list-columns-reverse') %>
          <%= t('actions.index') %>
        <% end %>
      </li>
      <!-- Admin section -->
      <% if current_user.admin %>
        <li class="nav-item d-inline-flex p-1">
          <%= link_to edit_project_path(@project),
                class: "icon-link btn btn-sm btn-warning actions",
                title: t('actions.edit') do %>
                <%== icon('pencil') %>
                <%= t('actions.edit') %>
          <% end %>
        </li>
      <% end %>
      <% if current_user.admin %>
        <li class="nav-item d-inline-flex p-1">
          <%= link_to @project,
                method: :delete,
                class: "icon-link btn btn-sm btn-danger actions",
                title: t('actions.delete'),
                data: { confirm: "Are you sure? Delete cannot be undone." } do %>
            <%== icon('trash') %>
            <%= t('actions.delete') %>
          <% end %>
        </li>
      <% end %>

      <li class="nav-item d-inline-flex p-1">
        <%= link_to @project.prev("code"),
              class: "icon-link btn btn-sm btn-secondary actions",
              title: t('actions.previous') do %>
          <%== icon('arrow-left') %>
          <%= t('actions.previous') %>
        <% end %>
      </li>

      <li class="nav-text h2 d-inline-flex p-1 ms-5 me-5">
        <%= @project.code + ": " + @project.title %>
      </li>

      <li class="nav-item d-inline-flex p-1">
        <%= link_to @project.next("code"),
              class: "icon-link btn btn-sm btn-secondary actions",
              title: t('actions.next') do %>
          <%= t('actions.next') %>
          <%== icon('arrow-right') %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

<%= render @project %>