config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    get 'site/home'
    get 'site/help'
    get 'site/about'
    get 'site/contact'

    devise_for :users
    resources :users, :only => [:show, :index]
    resources :projects
    resources :tags
    end

  # Defines the root path route ("/")
  root to: 'site#home'
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :project
  belongs_to :discipline

  attribute :full_tag, :string
  after_find :set_full_tag

  validates :prefix, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :prefix, length: { in: 1..6 }
  validates :serial, presence: true, inclusion: { in: 0..9999 }
  validates :suffix, length: { maximum: 5 }
  validates :description, length: { maximum: 40 }
  validates :phase, inclusion: { in: 0..10 }

  def self.ransackable_attributes(auth_object = nil)
    ["prefix", "serial", "suffix", "full_tag", "description", "phase", "created_at", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["discipline", "project"]
  end

  private

    def set_full_tag
    # Set the full_tag on the instance using self.full_tag
    self.full_tag = "#{prefix}-#{self.serial.to_s.rjust(4, '0')}"

    # Add suffix if it's present
    self.full_tag += ".#{suffix}" if suffix.present?
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]

  # GET /tags or /tags.json
  def index
    @q = Tag.ransack(params[:q])
    @pagy, @tags = pagy(@q.result.includes(:discipline, :project), limit: 10)
  end

  # GET /tags/1 or /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: "Tag was successfully created." }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_path, status: :see_other, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:prefix, :serial, :suffix, :description, :notes, :project_id, :discipline, :project_phase)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<div class="container-fluid">
  <%= bootstrap_form_with(model: @tag, layout: :horizontal) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="flex-row d-flex" >
      <div class="p-2"
        <%= f.text_field :prefix, layout: :vertical,
              help: t('activerecord.attributes.tag.prefix_help') %>
      </div>
      <div class="p-2"
        <%= f.number_field :serial, layout: :vertical,
              help: t('activerecord.attributes.tag.serial_help') %>
      </div>
      <div class="p-2"
        <%= f.text_field :suffix, layout: :vertical,
              help: t('activerecord.attributes.tag.suffix_help') %>
      </div>
    </div>

    <div class="flex-row d-flex" >
      <div class="p-2"
        prefix
      </div>
      <div class="p-2"
        serial
      </div>
      <div class="p-2"
        suffix
      </div>
    </div>

    <div class="flex-row d-flex" >
      <div class="p-2  w-75"
        <%= f.text_field :description, hide_label: true, required: true,
              placeholder: t('activerecord.attributes.tag.description'),
              help: t('activerecord.attributes.tag.description') %>
      </div>
    </div>
        <div class="flex-row d-flex" >
          <div class="p-2  w-75"
        <%= f.text_area :notes, hide_label: true,
              placeholder: t('activerecord.attributes.tag.notes') %>
      </div>
    </div>

    <div class="actions">
      <%= f.primary do %>
        <%= yield(:button_text) %>
        <%== icon('save') %>
      <% end %>
      <% if @tag.persisted? %>
        <%= link_to @tag, class: "btn btn-warning actions",
                data: { turbo_confirm: t('actions.sure') } do %>
                <%= t('actions.discard') %>
                <%== icon('x-square') %>
        <% end %>
      <% else %>
        <%= link_to tags_path, class: "btn btn-warning actions",
                data: { turbo_confirm: t('actions.sure') }  do %>
          <%= t('actions.discard') %>
          <%== icon('x-square') %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/tags/_tag.html.erb
<div id="<%= dom_id tag %>">
  <div class="container-fluid">
    <div class="d-flex flex-row mb-3">
      <p class="p2"><%= t('activerecord.attributes.discipline.code') %>:
      <%= tag.discipline.code %></p>
    </div>
    <div class="d-flex flex-row mb-3">
      <p class="p2"><%= t('activerecord.attributes.tag.full_tag') %>:
        <%= tag.full_tag %></p>
    </div>
    <div class="d-flex flex-row mb-3">
      <p class="p2"><%= t('activerecord.attributes.tag.description') %>:
        <%= tag.description %></p>
    </div>
    <div class="d-flex flex-row mb-3">
      <p class="p2"><%= t('activerecord.attributes.tag.notes') %>:
        <%= tag.notes %></p>
    </div>
    <div class="d-flex flex-row mb-3">
      <p class="p2"><%= t('activerecord.models.project') %>:
        <%= tag.project.code %></p>
    </div>
    <div class="d-flex flex-row mb-3">
      <p class="p2"><%= t('activerecord.attributes.tag.phase') %>:
        <%= tag.phase %></p>
    </div>
  </div>
</div>

app/views/tags/edit.html.erb
<% provide(:title, t('.title')) %>
<% provide(:button_text, t('actions.save')) %>
<h2>
  <%= t('.header', tag: @tag.full_tag)%>
</h2>
<%= render 'form' %>

app/views/tags/index.html.erb
<% provide(:title, t('.title')) %>
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0 flex-row">
      <li class="nav-item">
        <%= link_to new_tag_path, class: "btn btn-primary actions",
              aria: { label: t('actions.new') },
              title: t('actions.new')  do %>
          <%== icon('plus-square-fill') %>
          <%= t('actions.new') + " " + t('activerecord.models.tag') %>
        <% end %>
      </li>
      <span class="nav-text ms-3 me-3 h2">
        <%= t('.header')%>
      </span>
    </ul>
  </div>
</nav>
<div class = "container">
  <div class = 'listing'>
    <%= search_form_for @q do |f| %>
      <%= f.search_field :full_tag_or_description_cont, class: "search_field" %>
      <%= f.button nil, class: "btn btn-primary btn-sm", action: :submit do %>
        <%== icon('search') %>
      <% end %>
    <% end %>
    <%== pagy_bootstrap_nav(@pagy) %>
    <table id='tags' class='table table-responsive table-condensed table-striped table-hoverable table-bordered' >
      <thead>
        <th scope="col"><%= sort_link(@q, :discipline_code,
                  t('activerecord.attributes.tag.discipline')) %></th>
        <th scope="col"><%= sort_link(@q, :phase) %></th>
        <th scope="col"><%= sort_link(@q, :full_tag) %></th>
        <th scope="col"><%= sort_link(@q, :description) %></th>
        <th scope="col"><%= t('activerecord.attributes.tag.notes') %></th>
        <th scope="col" width="150px"><%= t('table.links')%></th>
      </thead>
      <tbody>
        <% @tags.each do |t| %>
          <tr scope="row">
            <td><%= t.discipline.code %></td>
            <td><%= t.phase %></td>
            <td><%= link_to t.full_tag, tag_path(t) %></td>
            <td><%= highlight t.description, params.dig(:q, :full_tag_or_description_cont)  %></td>
            <td><%= t.notes %></td>
            <td>
              <%= link_to tag_path(t), class: "btn btn-secondary btn-sm icon-link",
                    aria: { label: t('actions.show') },
                    title: t('actions.show'),
                    display: "inline" do %>
                <%== icon('eye') %>
              <% end %>
              <%= link_to edit_tag_path(t), class: "btn btn-warning btn-sm icon-link",
                    aria: { label: t('actions.edit') },
                    title: t('actions.edit'),
                    display: "inline"  do %>
                <%== icon('pencil') %>
              <% end %>
              <% if current_user && current_user.admin? %>
                <%= link_to p, method: :delete, class: "btn btn-danger btn-sm icon-link",
                      aria: { label: t('actions.delete') },
                      title: t('actions.delete'),
                      display: "inline"  do %>
                  <%== icon('trash') %>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%== pagy_bootstrap_nav(@pagy) %>
    <%== pagy_info(@pagy) %>


  </div>
</div>

app/views/tags/new.html.erb
<% provide(:title, t('.title')) %>
<% provide(:button_text, t('actions.save')) %>
<h2>
  <%= t('.header')%>
</h2>
<%= render 'form' %>

app/views/tags/show.html.erb
<% provide(:title, t('.title', tag: @tag.full_tag)) %>
<%# Header with navigation buttons. %>
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <ul class="navbar-nav flex-row page-heading">
      <li class="nav-item d-inline-flex p-1">
        <%= link_to tags_path,
              class: "icon-link btn btn-sm btn-secondary actions",
              title: t('actions.index') do %>
          <%== icon('list-columns-reverse') %>
          <%= t('actions.index') %>
        <% end %>
      </li>
      <!-- Admin section -->
      <% if current_user && current_user.admin %>
        <li class="nav-item d-inline-flex p-1">
          <%= link_to edit_tag_path(@tag),
                class: "icon-link btn btn-sm btn-warning actions",
                title: t('actions.edit') do %>
                <%== icon('pencil') %>
                <%= t('actions.edit') %>
          <% end %>
        </li>
      <% end %>
      <% if current_user && current_user.admin %>
        <li class="nav-item d-inline-flex p-1">
          <%= link_to @tag,
                method: :delete,
                class: "icon-link btn btn-sm btn-danger actions",
                title: t('actions.delete'),
                data: { confirm: "Are you sure? Delete cannot be undone." } do %>
            <%== icon('trash') %>
            <%= t('actions.delete') %>
          <% end %>
        </li>
      <% end %>

      <li class="nav-item d-inline-flex p-1">
        <%= link_to @tag.prev("id"),
              class: "icon-link btn btn-sm btn-secondary actions",
              title: t('actions.previous') do %>
          <%== icon('arrow-left') %>
          <%= t('actions.previous') %>
        <% end %>
      </li>

      <li class="nav-text h2 d-inline-flex p-1 ms-5 me-5">
        <%= t('.header', tag: @tag.full_tag) %>
      </li>

      <li class="nav-item d-inline-flex p-1">
        <%= link_to @tag.next("id"),
              class: "icon-link btn btn-sm btn-secondary actions",
              title: t('actions.next') do %>
          <%= t('actions.next') %>
          <%== icon('arrow-right') %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

<%= render @tag %>