config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    get 'site/home'
    get 'site/help'
    get 'site/about'
    get 'site/contact'

    devise_for :users
    resources :users, :only => [:show, :index]
    resources :projects
    resources :tags
    end

  # Defines the root path route ("/")
  root to: 'site#home'
end

app/views/layouts/_footer.html.erb
<div class="container-fluid">
  <footer class="footer border-top">
    <small>
      <ul>
        <li class="nav-item">
          <%= link_to t('menu.about'), site_about_path,
            class: ["nav-link", { active: current_page?(site_about_path) }],
            aria: { label: t('menu.about') } %>
        </li>
        <li class="nav-item">
          <%= link_to t('menu.help'), site_help_path,
            class: ['nav-link', { active: current_page?(site_help_path) }],
            aria: { label: t('menu.help') } %>
        </li>
      </ul>
      <div class="credits">
        <i> <%= t('credit', scope: 'footer') %></i>
        <a id = 'hidden-link'
          href = 'https://youtu.be/rVDBZFfDqB8?si=qvqS2soZoCEh63ZN'
          target="_blank">
          <%= t('walking', scope: 'rails') %>
        </a>
        <%= link_to image_tag("rails.png", alt: "Rails logo", size: "30"),
                    'http://rubyonrails.org/' %>
      </div>
    </small>
  </footer>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container-fluid">
    <div class="nav-item">
      <%= link_to root_path,
                class: ["navbar-brand", { active: current_page?(root_path) }],
                id: "logo" do %>
        <%= image_tag("favicon.ico") %>
        <%= t('app_name') %>
      <% end %>
    </div>

    <button class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to t('menu.about'), site_about_path,
            class: ["nav-link", { active: current_page?(site_about_path) }],
            aria: { label: t('menu.about') } %>
        </li>
        <li class="nav-item">
          <%= link_to t('menu.help'), site_help_path,
            class: ['nav-link', { active: current_page?(site_help_path) }],
            aria: { label: t('menu.help') } %>
        </li>

        <% if user_signed_in? %>
          <ul class="nav nav-tabs">
            <li class="nav-item">
              <%= link_to t('project', scope: 'activerecord.models').pluralize,
                projects_path,
                class: ['nav-link', { active: current_page?(controller: 'projects') }],
                aria: { label: t('project', scope: 'activerecord.models').pluralize } %>
            </li>
            <li class="nav-item">
              <%= link_to t('tag', scope: 'activerecord.models').pluralize,
                tags_path,
                class: "nav-link",
                aria: { label: t('tag', scope: 'activerecord.models').pluralize } %>
            </li>
          </ul>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle"
                href="#"
                data-bs-toggle="dropdown"
                id="user-menu-btn"
                role="button"
                aria-expanded="false">
              <%= current_user.name %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li class="nav-item"><%= link_to t('menu.profile'),
                  user_path(current_user),
                  class: "dropdown-item" %>
              </li>
              <li class="nav-item"><%= link_to t('menu.edit'),
                  edit_user_registration_path,
                  class: "dropdown-item" %>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li class="nav-item"><%= link_to t('menu.log_out'),
                  destroy_user_session_path,
                  data: { "turbo-method": :delete },
                  class: "dropdown-item" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to t('menu.log_in'),
                  new_user_session_path,
                  class: 'nav-link',
                  aria: { label: t('menu.log_in') } %>
          </li>
        <% end %>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#"
                id="navbarLocaleSelect"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false">
                <%= flag_icon(flag_code(locale)) %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% I18n.available_locales.each do |locale| %>
              <li class="nav-item">
                <%= flag_icon(flag_code(locale)) %>
                <% if I18n.locale == locale %>
                  <%= t(locale, scope: 'locales') %>
                <% else %>
                  <%= link_to t(locale, scope: 'locales'),
                              url_for(locale: locale) %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head lang="<%= I18n.locale %>">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= render 'layouts/shim' %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>

  </body>
</html>